version: '3.9'

services:
  notification-service:
    build:
      context: ./notification-service
    ports:
      - "8082:8082"

  main-service:
    build:
      context: ./main-service
    ports:
      - "6868:6868"

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8888:8888"
    image: bwnguyenvu/swd392-api-gateway
  integration-service:
    build:
      context: ./integration-service
    ports:
      - "8081:8081"
    image: bwnguyenvu/integration-service:latest

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: resellingFlowerDev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
